apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: s3-upload-sa-binding
subjects:
- kind: ServiceAccount
  name: s3-upload-sa
  namespace: s3-upload
roleRef:
  kind: ClusterRole
  name: s3-upload-cluster-role
  apiGroup: rbac.authorization.k8s.io
