apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-upload-sa
  namespace: s3-upload
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.awsAccountID }}:role/{{ .Values.env }}-eks-pod-upload-role
